# Generated by Django 5.2.1 on 2025-05-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="名称")),
                ("myimg", models.ImageField(upload_to="img/my_img", verbose_name="图片")),
            ],
            options={
                "verbose_name_plural": "测试存储",
            },
        ),
    ]
