# Generated by Django 5.2.1 on 2025-05-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MyImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("myimg", models.ImageField(upload_to="img/my_img", verbose_name="图片")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                ("image_name", models.CharField(max_length=64, verbose_name="图片名称")),
                (
                    "image_class",
                    models.SmallIntegerField(
                        choices=[
                            (1, "人像摄影"),
                            (2, "风光摄影"),
                            (3, "纪实摄影"),
                            (4, "静物摄影"),
                            (5, "街头摄影"),
                            (6, "野生动物摄影"),
                        ],
                        verbose_name="摄影类别",
                    ),
                ),
                (
                    "image_level",
                    models.SmallIntegerField(
                        choices=[
                            (1, "曝光与光影"),
                            (2, "对焦与清晰度"),
                            (3, "构图与画面结构"),
                            (4, "色彩与色调"),
                            (5, "视觉冲击力与美感"),
                            (6, "叙事性与故事感"),
                            (7, "风格与创新"),
                        ],
                        verbose_name="赏析角度",
                    ),
                ),
                ("page_view", models.IntegerField(verbose_name="浏览量")),
            ],
        ),
        migrations.DeleteModel(
            name="MyImage",
        ),
    ]
