# Generated by Django 5.2.1 on 2025-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0002_myimages_delete_myimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myimages",
            name="image_level",
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_color",
            field=models.TextField(default="无", verbose_name="视觉冲击力与美感"),
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_composition",
            field=models.TextField(default="无", verbose_name="构图与画面结构"),
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_exposure",
            field=models.TextField(default="无", verbose_name="曝光与光影"),
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_focus",
            field=models.TextField(default="无", verbose_name="对焦与清晰度"),
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_narrative",
            field=models.TextField(default="无", verbose_name="叙事性与故事感"),
        ),
        migrations.AddField(
            model_name="myimages",
            name="image_style",
            field=models.TextField(default="无", verbose_name="风格与创新"),
        ),
        migrations.AlterField(
            model_name="myimages",
            name="image_class",
            field=models.SmallIntegerField(
                choices=[
                    (1, "人像摄影"),
                    (2, "风光摄影"),
                    (3, "纪实摄影"),
                    (4, "静物摄影"),
                    (5, "街头摄影"),
                    (6, "野生动物摄影"),
                ],
                default=0,
                verbose_name="摄影类别",
            ),
        ),
        migrations.AlterField(
            model_name="myimages",
            name="image_name",
            field=models.CharField(default="NULL", max_length=64, verbose_name="图片名称"),
        ),
        migrations.AlterField(
            model_name="myimages",
            name="page_view",
            field=models.IntegerField(default=0, verbose_name="浏览量"),
        ),
    ]
