# Generated by Django 5.2.1 on 2025-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app01", "0003_remove_myimages_image_level_myimages_image_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="myimages",
            name="numbers_of_likes",
            field=models.IntegerField(default=0, verbose_name="点赞量"),
        ),
    ]
